# Generated by Django 5.1 on 2024-09-14 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stamp_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
